#!/bin/bash
# ============================================================================
# gentoo_install_part2.sh - Stage3 + chroot prep
# Dell / optiplex-3090 - Run from live USB after part1
# ============================================================================
# Prerequisites: part1 completed, /mnt/gentoo mounted
# After this: enter chroot and run gentoo_install_part3_chroot.sh
# ============================================================================
# Generated by tools/generate-install.sh from base 'precision-t5810'.
# Config file copies are conditional — only files present in the machine's
# directory (machines/optiplex-3090/) are copied. Hand-edit the fstab tmpfs
# sizing and any dual-storage entries before running.
# ============================================================================

set -euo pipefail
[[ $EUID -ne 0 ]] && echo "ERROR: Must run as root (sudo)" && exit 1

GENTOO="/mnt/gentoo"
MIRROR="https://gentoo.osuosl.org"
STAGE3_DIR="releases/amd64/autobuilds/current-stage3-amd64-desktop-openrc"
STAGE3_FALLBACK="stage3-amd64-desktop-openrc-20260222T170100Z.tar.xz"
MACHINE="optiplex-3090"
CONFIG_STAGE="/root/${MACHINE}-configs"

# Target disk (must match part1). PART_PREFIX handles nvme "p" vs sata bare.
TARGET="/dev/nvme0n1"
PART_PREFIX="${TARGET}p"

# ============================================================================
# Auto-discover latest stage3 (fallback to hardcoded on offline)
# ============================================================================
echo "Checking mirror for latest stage3..."
STAGE3_FILE=""
if command -v wget &>/dev/null; then
    LATEST=$(wget -qO- "${MIRROR}/${STAGE3_DIR}/latest-stage3-amd64-desktop-openrc.txt" 2>/dev/null \
        | grep -v '^#' | grep 'stage3' | head -1 | awk '{print $1}' | xargs basename 2>/dev/null)
    [[ -n "$LATEST" ]] && STAGE3_FILE="$LATEST"
elif command -v curl &>/dev/null; then
    LATEST=$(curl -sfL "${MIRROR}/${STAGE3_DIR}/latest-stage3-amd64-desktop-openrc.txt" 2>/dev/null \
        | grep -v '^#' | grep 'stage3' | head -1 | awk '{print $1}' | xargs basename 2>/dev/null)
    [[ -n "$LATEST" ]] && STAGE3_FILE="$LATEST"
fi
if [[ -z "$STAGE3_FILE" ]]; then
    echo "  Mirror unreachable — using fallback: $STAGE3_FALLBACK"
    STAGE3_FILE="$STAGE3_FALLBACK"
else
    echo "  Found: $STAGE3_FILE"
fi
STAGE3_URL="${MIRROR}/${STAGE3_DIR}/${STAGE3_FILE}"
DIGESTS_URL="${STAGE3_URL}.DIGESTS"

# Locate gentoo-machines repo on the live USB
REPO=""
for candidate in \
    /home/liveuser/ai/gentoo-machines \
    /home/liveuser/gentoo-machines \
    /home/chris/ai/gentoo-machines \
    /run/media/liveuser/VTOYEFI/gentoo-machines; do
    [[ -d "$candidate" ]] && REPO="$candidate" && break
done
if [[ -z "$REPO" ]]; then
    echo "ERROR: gentoo-machines repo not found. Clone or mount it first."
    exit 1
fi
CONFIGS="$REPO/machines/$MACHINE"

echo "=== Gentoo Install Part 2: Stage3 + Chroot Prep ==="
echo "    Machine: $MACHINE"
echo "    Repo:    $REPO"
echo "    Configs: $CONFIGS"
echo ""

# ============================================================================
# PRE-FLIGHT
# ============================================================================
for mp in "$GENTOO" "$GENTOO/boot" "$GENTOO/boot/efi"; do
    if ! mountpoint -q "$mp"; then
        echo "ERROR: $mp is not mounted. Run part1 first."
        exit 1
    fi
done
echo "[OK] Filesystems mounted."

[[ -d "$CONFIGS" ]] || { echo "ERROR: $CONFIGS not found in repo."; exit 1; }
echo "[OK] Config files found at $CONFIGS."
echo ""

# ============================================================================
# STEP 1: DOWNLOAD STAGE3
# ============================================================================
echo "[STEP 1] Downloading stage3 tarball..."
echo "  URL: $STAGE3_URL"
cd "$GENTOO"
if [[ ! -f "$STAGE3_FILE" ]]; then
    wget --progress=bar:force "$STAGE3_URL" -O "$STAGE3_FILE" --no-check-certificate
else
    echo "  Stage3 already downloaded, skipping."
fi
wget -q "$DIGESTS_URL" -O "${STAGE3_FILE}.DIGESTS" --no-check-certificate
echo ""

# ============================================================================
# STEP 2: VERIFY INTEGRITY
# ============================================================================
echo "[STEP 2] Verifying stage3 integrity..."
EXPECTED_SHA512=$(grep -A1 'SHA512' "${STAGE3_FILE}.DIGESTS" | grep "$STAGE3_FILE" | grep -v '.CONTENTS' | awk '{print $1}')
if [[ -n "$EXPECTED_SHA512" ]]; then
    ACTUAL_SHA512=$(sha512sum "$STAGE3_FILE" | awk '{print $1}')
    if [[ "$EXPECTED_SHA512" == "$ACTUAL_SHA512" ]]; then
        echo "  [OK] SHA512 checksum verified."
    else
        echo "  [FAIL] SHA512 mismatch!"
        echo "  Expected: $EXPECTED_SHA512"
        echo "  Got:      $ACTUAL_SHA512"
        exit 1
    fi
else
    echo "  WARNING: Could not extract SHA512 — proceeding without verification."
fi
echo ""

# ============================================================================
# STEP 3: EXTRACT STAGE3
# ============================================================================
echo "[STEP 3] Extracting stage3 to $GENTOO..."
tar xpf "$STAGE3_FILE" --xattrs-include='*.*' --numeric-owner -C "$GENTOO"
echo "  [OK] Stage3 extracted."
rm -f "$STAGE3_FILE" "${STAGE3_FILE}.DIGESTS"
echo ""

# ============================================================================
# STEP 4: COPY CONFIGURATION FILES
# ============================================================================
echo "[STEP 4] Installing configuration files..."
mkdir -p "$GENTOO$CONFIG_STAGE"

# Copy a file from $CONFIGS to a target path if it exists.
copy_if_exists() {
    local src="$1" dst="$2" label="${3:-$(basename "$1")}"
    if [[ -f "$src" ]]; then
        mkdir -p "$(dirname "$dst")"
        cp "$src" "$dst"
        echo "  [OK] $label"
    fi
}

# --- Portage config (make.conf + env) ---
copy_if_exists "$CONFIGS/make.conf"                 "$GENTOO/etc/portage/make.conf"               "make.conf"
copy_if_exists "$CONFIGS/package.env"               "$GENTOO/etc/portage/package.env"             "package.env"
copy_if_exists "$CONFIGS/portage_env_notmpfs.conf"  "$GENTOO/etc/portage/env/notmpfs.conf"        "env/notmpfs.conf"
copy_if_exists "$CONFIGS/package.use"               "$GENTOO/etc/portage/package.use/$MACHINE"    "package.use -> $MACHINE"
copy_if_exists "$CONFIGS/package.accept_keywords"   "$GENTOO/etc/portage/package.accept_keywords/$MACHINE" "package.accept_keywords -> $MACHINE"

# --- Kernel config + world + grub staged for chroot ---
copy_if_exists "$CONFIGS/kernel_config.sh"          "$GENTOO$CONFIG_STAGE/kernel_config.sh"       "kernel_config.sh"
[[ -f "$GENTOO$CONFIG_STAGE/kernel_config.sh" ]] && chmod +x "$GENTOO$CONFIG_STAGE/kernel_config.sh"
copy_if_exists "$CONFIGS/world"                     "$GENTOO$CONFIG_STAGE/world"                  "world"
copy_if_exists "$CONFIGS/grub"                      "$GENTOO$CONFIG_STAGE/grub"                   "grub"
copy_if_exists "$CONFIGS/zram-init.conf"            "$GENTOO$CONFIG_STAGE/zram-init.conf"         "zram-init.conf"

# --- sysctl tuning (name varies per machine; check both forms) ---
if [[ -f "$CONFIGS/sysctl-performance.conf" ]]; then
    mkdir -p "$GENTOO/etc/sysctl.d"
    cp "$CONFIGS/sysctl-performance.conf" "$GENTOO/etc/sysctl.d/99-$MACHINE-performance.conf"
    echo "  [OK] sysctl-performance.conf -> /etc/sysctl.d/"
fi

# --- NVIDIA-specific config ---
copy_if_exists "$CONFIGS/prime-run"                 "$GENTOO$CONFIG_STAGE/prime-run"              "prime-run (NVIDIA PRIME wrapper)"
copy_if_exists "$CONFIGS/99-module-rebuild.install" "$GENTOO$CONFIG_STAGE/99-module-rebuild.install" "99-module-rebuild.install"

# --- Shared portage files ---
for f in package.use package.accept_keywords package.license; do
    copy_if_exists "$REPO/shared/$f" "$GENTOO/etc/portage/$f/shared" "shared/$f"
done

# --- Shared desktop restore scripts ---
for f in restore-desktop.sh restore-system.sh xfce4-keybindings.sh xfce4-panel.sh openrc-services; do
    copy_if_exists "$REPO/shared/$f" "$GENTOO$CONFIG_STAGE/$f" "shared/$f"
done

# --- Shared startup hooks ---
if [[ -f "$REPO/shared/ksm.start" ]]; then
    mkdir -p "$GENTOO/etc/local.d"
    cp "$REPO/shared/ksm.start" "$GENTOO/etc/local.d/ksm.start"
    chmod +x "$GENTOO/etc/local.d/ksm.start"
    echo "  [OK] ksm.start -> /etc/local.d/"
fi
if [[ -f "$REPO/shared/fstrim-weekly" ]]; then
    mkdir -p "$GENTOO/etc/local.d"
    cp "$REPO/shared/fstrim-weekly" "$GENTOO/etc/local.d/fstrim-weekly.start"
    chmod +x "$GENTOO/etc/local.d/fstrim-weekly.start"
    echo "  [OK] fstrim-weekly -> /etc/local.d/"
fi
if [[ -f "$REPO/shared/35-intel-microcode.install" ]]; then
    mkdir -p "$GENTOO/etc/kernel/preinst.d"
    cp "$REPO/shared/35-intel-microcode.install" "$GENTOO/etc/kernel/preinst.d/35-intel-microcode.install"
    chmod +x "$GENTOO/etc/kernel/preinst.d/35-intel-microcode.install"
    echo "  [OK] 35-intel-microcode.install -> /etc/kernel/preinst.d/"
fi

# --- LightDM config (shared) ---
copy_if_exists "$REPO/shared/lightdm.conf"          "$GENTOO$CONFIG_STAGE/lightdm.conf"           "shared lightdm.conf"
copy_if_exists "$REPO/shared/logind.conf"           "$GENTOO$CONFIG_STAGE/logind.conf"            "shared logind.conf"

# --- Chroot install script ---
cp "$CONFIGS/gentoo_install_part3_chroot.sh" "$GENTOO/root/"
chmod +x "$GENTOO/root/gentoo_install_part3_chroot.sh"
echo "  [OK] gentoo_install_part3_chroot.sh -> /root/"
echo ""

# ============================================================================
# STEP 5: CONFIGURE DNS
# ============================================================================
echo "[STEP 5] Configuring DNS for chroot..."
cp -L /etc/resolv.conf "$GENTOO/etc/resolv.conf"
echo "  [OK] resolv.conf copied."
echo ""

# ============================================================================
# STEP 6: MOUNT PSEUDO-FILESYSTEMS
# ============================================================================
echo "[STEP 6] Mounting pseudo-filesystems for chroot..."
mount --types proc /proc "$GENTOO/proc"
mount --rbind /sys "$GENTOO/sys";  mount --make-rslave "$GENTOO/sys"
mount --rbind /dev "$GENTOO/dev";  mount --make-rslave "$GENTOO/dev"
mount --bind  /run "$GENTOO/run";  mount --make-slave  "$GENTOO/run"
echo "  [OK] proc, sys, dev, run mounted."
echo ""

# ============================================================================
# STEP 7: PORTAGE BUILD DIRECTORIES
# ============================================================================
echo "[STEP 7] Creating portage build directories..."
mkdir -p "$GENTOO/var/tmp/portage" "$GENTOO/var/tmp/portage-disk"
echo "  [OK] /var/tmp/portage and /var/tmp/portage-disk created."
echo ""

# ============================================================================
# STEP 8: GRAB UUIDs
# ============================================================================
echo "[STEP 8] Partition UUIDs for fstab:"
UUID_EFI=$(blkid -s UUID -o value "${PART_PREFIX}1" 2>/dev/null || echo 'UNKNOWN')
UUID_BOOT=$(blkid -s UUID -o value "${PART_PREFIX}2" 2>/dev/null || echo 'UNKNOWN')
UUID_ROOT=$(blkid -s UUID -o value "${PART_PREFIX}3" 2>/dev/null || echo 'UNKNOWN')
echo "  EFI  (${PART_PREFIX}1): $UUID_EFI"
echo "  BOOT (${PART_PREFIX}2): $UUID_BOOT"
echo "  ROOT (${PART_PREFIX}3): $UUID_ROOT"
echo ""

cat > "$GENTOO$CONFIG_STAGE/disk-uuids.txt" <<EOF
UUID_EFI=$UUID_EFI
UUID_BOOT=$UUID_BOOT
UUID_ROOT=$UUID_ROOT
EOF
echo "  [OK] UUIDs saved to $CONFIG_STAGE/disk-uuids.txt"
echo ""

# ============================================================================
# STEP 9: GENERATE FSTAB
# ============================================================================
echo "[STEP 9] Generating /etc/fstab..."
# NOTE: Hand-edit tmpfs size below to fit the machine's RAM. 4G is safe for
# 8GB-RAM boxes; larger machines can afford 8-46GB.
cat > "$GENTOO/etc/fstab" <<FSTAB
# /etc/fstab - $MACHINE Gentoo
# Generated by gentoo_install_part2.sh

# <device>              <mount>          <fs>   <opts>                                                          <dump> <pass>
UUID=$UUID_ROOT         /                ext4   defaults,noatime                                                 0      1
UUID=$UUID_BOOT         /boot            ext4   defaults,noatime                                                 0      2
UUID=$UUID_EFI          /boot/efi        vfat   defaults,noatime,umask=0077                                      0      0

# Portage tmpfs — 7G (16GB RAM, CONSTRAINED build profile, disk fallback for chromium/llvm/rust)
tmpfs                   /var/tmp/portage tmpfs  size=7G,uid=portage,gid=portage,mode=775,nosuid,noatime,nodev   0 0
FSTAB
echo "  [OK] /etc/fstab generated (review tmpfs size)."
echo ""

# ============================================================================
# DONE
# ============================================================================
echo "============================================================"
echo "=== Ready to chroot into Gentoo! ==="
echo "============================================================"
echo ""
echo "Enter the chroot:"
echo "  sudo chroot $GENTOO /bin/bash"
echo "  source /etc/profile"
echo '  export PS1="(chroot) \[\033[0;31m\]\u@\h \[\033[0;36m\]\w \$ \[\033[0m\]"'
echo ""
echo "Then run: bash /root/gentoo_install_part3_chroot.sh"
