#!/bin/bash
# ============================================================================
# gentoo_install_part1.sh - Partition NVME disk for Dell / optiplex-3090
# Run from Gentoo or Fedora live USB
# ============================================================================
# Target layout on ${TARGET}:
#   part1  600MB   EFI System Partition  (FAT32)   -> /boot/efi
#   part2  2GB     Boot partition        (ext4)    -> /boot
#   part3  rest    Root partition        (ext4)    -> /
#   No swap partition — zram is configured in part3.
#
# PRE-REQUISITES:
#   - Secure Boot disabled in firmware
#   - Booted from a live USB (Gentoo minimal or Fedora)
#   - Network connected
# ============================================================================
# Generated by tools/generate-install.sh from base 'precision-t5810'.
# Review all TODOs before running. This is a starting skeleton, not a
# production-ready script — verify TARGET, partition sizes, and any
# machine-specific safety blocks (e.g., boot-media exclusions).
# ============================================================================

set -euo pipefail
[[ $EUID -ne 0 ]] && echo "ERROR: Must run as root (sudo)" && exit 1

# --- Disks detected in harvest (for reference) -------------------------------
# Harvest only saw the Ventoy USB (/dev/sda 57.8G) — internal 256GB NVMe is
# hidden by Intel RST/RAID mode in BIOS. Before running this script:
#   1. Reboot, F2 → BIOS → Storage → SATA Operation: RAID On → AHCI
#   2. Save & reboot to live USB
#   3. Verify `lsblk` shows /dev/nvme0n1 (~238GiB)

# --- Machine-specific config (edit these) ------------------------------------
TARGET="/dev/nvme0n1"
PART_PREFIX="${TARGET}p"
EFI_END_MIB=601
BOOT_END_MIB=2649

# --- TODO: boot-media exclusion ----------------------------------------------
# On workstations booting from a known USB, add an explicit device-ID guard.
# Example (Precision T5810 with SABRENT Ventoy USB):
#   VENTOY_USB_ID="SABRENT_DD56419883896"
#   TARGET_DEVICE_ID=$(udevadm info --query=property --name="$TARGET" | grep ^ID_SERIAL=)
#   echo "$TARGET_DEVICE_ID" | grep -q "$VENTOY_USB_ID" && \
#       { echo "FATAL: Target is boot USB"; exit 99; }

# ============================================================================
# PRE-FLIGHT: Verify tools exist
# ============================================================================
echo "=== Gentoo Install Part 1: Disk Wipe & Partition ==="
echo "    Target: $TARGET"
echo ""

MISSING=()
for tool in parted mkfs.ext4 mkfs.vfat blkid mount lsblk partprobe; do
    command -v "$tool" &>/dev/null || MISSING+=("$tool")
done
if [[ ${#MISSING[@]} -gt 0 ]]; then
    echo "ERROR: Missing tools: ${MISSING[*]}"
    echo "On Fedora: dnf install -y parted e2fsprogs dosfstools util-linux"
    exit 1
fi
echo "[OK] All required tools found."
echo ""

# ============================================================================
# SAFETY: Target must exist, not be USB, not be Ventoy
# ============================================================================
[[ -b "$TARGET" ]] || { echo "ERROR: $TARGET does not exist"; lsblk; exit 1; }

TARGET_TRAN=$(lsblk -ndo TRAN "$TARGET" 2>/dev/null || echo unknown)
if [[ "$TARGET_TRAN" == "usb" ]]; then
    echo "ERROR: $TARGET reports transport=usb — refusing to wipe install media."
    exit 1
fi

TARGET_MODEL=$(lsblk -ndo MODEL "$TARGET" 2>/dev/null || echo unknown)
if [[ "$TARGET_MODEL" == *Ventoy* ]] || [[ "$TARGET_MODEL" == *VTOY* ]]; then
    echo "ERROR: $TARGET model is '$TARGET_MODEL' — refusing to wipe install media."
    exit 1
fi

echo "[PRE-FLIGHT] Target disk identity:"
echo "  Device:    $TARGET"
echo "  Model:     $TARGET_MODEL"
echo "  Transport: $TARGET_TRAN"
echo ""
echo "[PRE-FLIGHT] Current disk layout:"
lsblk -o NAME,SIZE,TYPE,TRAN,FSTYPE,MOUNTPOINT,MODEL "$TARGET"
echo ""

# Check nothing on the target is mounted
MOUNTED=$(mount | grep "^${PART_PREFIX}" || true)
if [[ -n "$MOUNTED" ]]; then
    echo "WARNING: Partitions on $TARGET are currently mounted:"
    echo "$MOUNTED"
    read -p "Unmount them automatically? (y/N): " umount_confirm
    if [[ "$umount_confirm" == "y" || "$umount_confirm" == "Y" ]]; then
        for part in "${PART_PREFIX}"*; do
            umount "$part" 2>/dev/null || true
        done
        # Common live-USB mount points
        umount /mnt/fedora/boot /mnt/fedora /mnt/gentoo/boot/efi /mnt/gentoo/boot /mnt/gentoo 2>/dev/null || true
        echo "  Unmounted."
    else
        echo "Unmount manually and re-run."
        exit 1
    fi
    echo ""
fi

echo "*** THIS WILL DESTROY ALL DATA ON $TARGET ***"
echo "    Model: $TARGET_MODEL"
read -p "Type 'YES' to proceed: " confirm
[[ "$confirm" != "YES" ]] && { echo "Aborted."; exit 0; }

# ============================================================================
# STEP 1: Create fresh GPT partition table
# ============================================================================
echo ""
echo "[STEP 1] Creating fresh GPT partition table on $TARGET..."
parted -s "$TARGET" mklabel gpt
echo "  GPT table created."
echo ""

# ============================================================================
# STEP 2: Create partitions
# ============================================================================
echo "[STEP 2] Creating partitions..."
parted -s "$TARGET" mkpart "EFI"  fat32 1MiB ${EFI_END_MIB}MiB
parted -s "$TARGET" set 1 esp on
echo "  part1: 600MB EFI System Partition (esp flag set)"

parted -s "$TARGET" mkpart "BOOT" ext4  ${EFI_END_MIB}MiB ${BOOT_END_MIB}MiB
echo "  part2: 2GB Boot partition"

parted -s "$TARGET" mkpart "ROOT" ext4  ${BOOT_END_MIB}MiB 100%
echo "  part3: remainder for Root partition"
echo ""

partprobe "$TARGET" 2>/dev/null || true
sleep 2

# ============================================================================
# STEP 3: Verify layout
# ============================================================================
echo "[STEP 3] Verifying partition layout..."
parted -s "$TARGET" print
echo ""
lsblk -o NAME,SIZE,TYPE,PARTLABEL "$TARGET"
echo ""

read -p "Layout look correct? (y/N): " layout_ok
if [[ "$layout_ok" != "y" && "$layout_ok" != "Y" ]]; then
    echo "Aborted. Partitions created but not formatted."
    echo "Wipe and start over with: parted -s $TARGET mklabel gpt"
    exit 1
fi

# ============================================================================
# STEP 4: Format partitions
# ============================================================================
echo "[STEP 4] Formatting partitions..."
echo "  Formatting ${PART_PREFIX}1 as FAT32 (EFI)..."
mkfs.vfat -F 32 -n EFI "${PART_PREFIX}1"
echo "  Formatting ${PART_PREFIX}2 as ext4 (boot)..."
mkfs.ext4 -L BOOT -q "${PART_PREFIX}2"
echo "  Formatting ${PART_PREFIX}3 as ext4 (root)..."
mkfs.ext4 -L ROOT -q "${PART_PREFIX}3"
echo ""
echo "  All partitions formatted."
echo ""

# ============================================================================
# STEP 5: Report UUIDs
# ============================================================================
echo "[STEP 5] Final disk layout:"
lsblk -o NAME,SIZE,TYPE,FSTYPE,PARTLABEL,LABEL "$TARGET"
echo ""

echo "UUIDs (saved for part2 fstab generation):"
echo "  EFI  (${PART_PREFIX}1): $(blkid -s UUID -o value "${PART_PREFIX}1")"
echo "  BOOT (${PART_PREFIX}2): $(blkid -s UUID -o value "${PART_PREFIX}2")"
echo "  ROOT (${PART_PREFIX}3): $(blkid -s UUID -o value "${PART_PREFIX}3")"
echo ""

for part in "${PART_PREFIX}1" "${PART_PREFIX}2" "${PART_PREFIX}3"; do
    UUID=$(blkid -s UUID -o value "$part" 2>/dev/null || true)
    if [[ -z "$UUID" ]]; then
        echo "ERROR: $part has no UUID — format may have failed"
        exit 1
    fi
done
echo "[OK] All partitions verified."
echo ""

# ============================================================================
# STEP 6: Mount for Gentoo install
# ============================================================================
echo "[STEP 6] Mounting for Gentoo installation..."
mkdir -p /mnt/gentoo
mount "${PART_PREFIX}3" /mnt/gentoo
echo "  ${PART_PREFIX}3 -> /mnt/gentoo"

mkdir -p /mnt/gentoo/boot
mount "${PART_PREFIX}2" /mnt/gentoo/boot
echo "  ${PART_PREFIX}2 -> /mnt/gentoo/boot"

mkdir -p /mnt/gentoo/boot/efi
mount "${PART_PREFIX}1" /mnt/gentoo/boot/efi
echo "  ${PART_PREFIX}1 -> /mnt/gentoo/boot/efi"

echo ""
echo "=== Disk ready for Gentoo installation ==="
df -h /mnt/gentoo /mnt/gentoo/boot /mnt/gentoo/boot/efi
echo ""
echo "Next: run gentoo_install_part2.sh"
