#!/bin/bash
# ============================================================================
# gentoo_install_part3_chroot.sh - ONE-SHOT chroot install
# Dell / optiplex-3090 - Run INSIDE the chroot
# ============================================================================
# USAGE:
#   sudo chroot /mnt/gentoo /bin/bash
#   source /etc/profile
#   export PS1="(chroot) $PS1"
#   bash /root/gentoo_install_part3_chroot.sh
# ============================================================================
# Generated by tools/generate-install.sh from base 'precision-t5810'.
# Review all phases before running. This is a skeleton — machine-specific
# hardware quirks (NVIDIA kernel params, applesmc, HiDPI, Surface IPTS) may
# need hand-editing in Phase 11.
# ============================================================================

# NOTE: no `-u` (nounset) — /etc/profile.d files reference unbound vars.
set -eo pipefail

MACHINE="optiplex-3090"
HOSTNAME_SHORT="optiplex-3090"
CONFIGS="/root/${MACHINE}-configs"
TIMEZONE="America/New_York"
read -rp "Username for desktop user [chris]: " USERNAME
USERNAME="${USERNAME:-chris}"
NPROC=$(nproc)

echo "============================================================"
echo "=== Dell / optiplex-3090 — One-Shot Chroot Install ==="
echo "============================================================"

if [[ ! -f "$CONFIGS/kernel_config.sh" ]]; then
    echo "ERROR: Config files not found at $CONFIGS"
    echo "Are you inside the chroot? Did part2 run?"
    exit 1
fi


# ============================================================================
# PHASE 1: Bootstrap
# ============================================================================
echo ""
echo "=== PHASE 1: Bootstrap ==="

source /etc/profile
export PS1="(chroot) ${PS1:-}"

echo "[1.1] Syncing portage tree..."
emerge-webrsync
emerge --sync

echo "[1.2] Setting profile..."
eselect profile list
eselect profile set default/linux/amd64/23.0

echo "[1.3] Updating @world with USE flags..."
emerge --verbose --update --deep --newuse @world

echo "[OK] Phase 1 complete."

# ============================================================================
# PHASE 2: Kernel + Firmware
# ============================================================================
echo ""
echo "=== PHASE 2: Kernel + Firmware ==="

echo "[2.1] Installing kernel sources and firmware..."
emerge --verbose sys-kernel/gentoo-sources \
    sys-kernel/linux-firmware \
    sys-firmware/intel-microcode \
    sys-kernel/installkernel

echo "[2.2] Selecting kernel..."
eselect kernel list
eselect kernel set 1
ls -l /usr/src/linux

echo "[2.3] Configuring kernel..."
cd /usr/src/linux
if [[ -f "$CONFIGS/base.config" ]]; then
    cp "$CONFIGS/base.config" .config
    echo "  [OK] Base config copied"
else
    echo "  [INFO] No base.config — starting from defconfig"
    make defconfig
fi

bash "$CONFIGS/kernel_config.sh"

echo "[2.4] Resolving kernel config dependencies..."
make olddefconfig

echo ""
read -p "Open menuconfig for review? (y/N): " do_menuconfig
if [[ "$do_menuconfig" == "y" || "$do_menuconfig" == "Y" ]]; then
    make menuconfig
fi

echo "[2.5] Building kernel (make -j$NPROC)..."
make -j"$NPROC"

echo "[2.6] Installing kernel modules..."
make modules_install

echo "[2.7] Installing kernel..."
make install

echo "[2.8] Verifying kernel installation..."
ls -la /boot/vmlinuz-* /boot/config-* /boot/System.map-*

echo "[OK] Phase 2 complete."

# ============================================================================
# PHASE 3: Bootloader (GRUB)
# ============================================================================
echo ""
echo "=== PHASE 3: Bootloader ==="

echo "[3.1] Installing GRUB..."
emerge --verbose sys-boot/grub

echo "[3.2] Installing GRUB to EFI..."
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Gentoo

# EFI fallback path — some firmwares only boot EFI/Boot/bootx64.efi
echo "[3.2.1] Copying GRUB to EFI fallback path..."
mkdir -p /boot/efi/EFI/Boot
cp /boot/efi/EFI/Gentoo/grubx64.efi /boot/efi/EFI/Boot/bootx64.efi

echo "[3.3] Installing GRUB defaults..."
if [[ -f "$CONFIGS/grub" ]]; then
    cp "$CONFIGS/grub" /etc/default/grub
    echo "  [OK] /etc/default/grub installed"
else
    echo "  [WARN] No grub defaults found — using distribution defaults"
fi

echo "[3.4] Generating GRUB config..."
grub-mkconfig -o /boot/grub/grub.cfg

echo "[3.5] Verifying GRUB sees kernel..."
grep menuentry /boot/grub/grub.cfg

echo "[OK] Phase 3 complete."

# ============================================================================
# PHASE 4: System Configuration
# ============================================================================
echo ""
echo "=== PHASE 4: System Configuration ==="

echo "[4.1] Setting timezone to $TIMEZONE..."
ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime

echo "[4.2] Configuring locale..."
sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
grep -q "^en_US.UTF-8 UTF-8" /etc/locale.gen || echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
eselect locale set en_US.utf8
env-update && source /etc/profile

echo "[4.3] Setting hostname..."
echo "$HOSTNAME_SHORT" > /etc/hostname
cat > /etc/hosts <<EOF
127.0.0.1       localhost
::1             localhost
127.0.1.1       ${HOSTNAME_SHORT}.localdomain ${HOSTNAME_SHORT}
EOF

echo ""
echo "[4.4] Set root password:"
passwd

groupadd -f plugdev

echo "[4.5] Creating user '$USERNAME'..."
useradd -m -G wheel,audio,video,usb,input,plugdev -s /bin/bash "$USERNAME"
echo "Set password for user '$USERNAME':"
passwd "$USERNAME"
echo "%wheel ALL=(ALL:ALL) ALL" >> /etc/sudoers

echo "[4.6] Relaxing pam_faillock (home machine: 10 attempts, 5 min lockout)..."
sed -i 's/pam_faillock.so preauth/pam_faillock.so preauth deny=10 unlock_time=300/' /etc/pam.d/system-auth || true
sed -i 's/pam_faillock.so authfail/pam_faillock.so authfail deny=10 unlock_time=300/' /etc/pam.d/system-auth || true

echo "[OK] Phase 4 complete."

# ============================================================================
# PHASE 5: Networking
# ============================================================================
echo ""
echo "=== PHASE 5: Networking ==="

echo "[5.1] Installing networking packages..."
emerge --verbose net-wireless/wpa_supplicant \
    net-misc/networkmanager \
    net-misc/dhcpcd \
    gnome-extra/nm-applet \
    net-wireless/wireless-regdb \
    net-wireless/wireless-tools

echo "[5.2] Enabling NetworkManager..."
rc-update add NetworkManager default

echo "[OK] Phase 5 complete."

# ============================================================================
# PHASE 6: All Remaining Packages
# ============================================================================
echo ""
echo "=== PHASE 6: All Packages ==="

echo "[6.1] Installing world file..."
cp "$CONFIGS/world" /var/lib/portage/world

echo "[6.2] Installing all packages (may take 1-4 hours)..."
emerge --verbose --update --deep --newuse @world

echo ""
echo "[6.3] Merging updated config files..."
dispatch-conf || echo "  [WARN] dispatch-conf failed — run manually"

echo "[OK] Phase 6 complete."

# ============================================================================
# PHASE 7: Portage Infrastructure
# ============================================================================
echo ""
echo "=== PHASE 7: Portage Infrastructure ==="

mkdir -p /var/tmp/portage /var/tmp/portage-disk
chown portage:portage /var/tmp/portage /var/tmp/portage-disk

echo "[7.1] Verifying package.env..."
cat /etc/portage/package.env 2>/dev/null || echo "  [WARN] package.env not found"
cat /etc/portage/env/notmpfs.conf 2>/dev/null || echo "  [WARN] notmpfs.conf not found"

echo "[OK] Phase 7 complete."

# ============================================================================
# PHASE 8: OpenRC Services
# ============================================================================
echo ""
echo "=== PHASE 8: OpenRC Services ==="

rc-update add dbus default
rc-update add elogind boot
rc-update add acpid default
rc-update add cronie default
rc-update add display-manager default
rc-update add sshd default
rc-update add metalog default
rc-update add local default
rc-update add netmount default
rc-update add zram-init boot
rc-update add alsasound boot
rc-update add chronyd default
rc-update add thermald default

echo "[8.2] Enabling SSH pubkey authentication..."
sed -i 's/^#PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config

echo ""
echo "[8.3] Current runlevels:"
echo "  Default:"; rc-update show default
echo "  Boot:";    rc-update show boot

echo "[OK] Phase 8 complete."

# ============================================================================
# PHASE 9: Display Manager (LightDM + XFCE)
# ============================================================================
echo ""
echo "=== PHASE 9: LightDM + XFCE ==="

ls /usr/share/xsessions/ || echo "  [WARN] No xsessions!"

if [[ -f "$CONFIGS/lightdm.conf" ]]; then
    cp "$CONFIGS/lightdm.conf" /etc/lightdm/lightdm.conf
    echo "  [OK] machine lightdm.conf installed"
else
    sed -i 's/^#user-session=.*/user-session=xfce/' /etc/lightdm/lightdm.conf 2>/dev/null || true
    sed -i 's|^#session-wrapper=.*|session-wrapper=/etc/lightdm/Xsession|' /etc/lightdm/lightdm.conf 2>/dev/null || true
fi

sed -i 's/DISPLAYMANAGER=".*"/DISPLAYMANAGER="lightdm"/' /etc/conf.d/display-manager 2>/dev/null || \
    echo 'DISPLAYMANAGER="lightdm"' > /etc/conf.d/display-manager

echo "[OK] Phase 9 complete."

# ============================================================================
# PHASE 10: PipeWire Audio
# ============================================================================
echo ""
echo "=== PHASE 10: PipeWire Audio ==="

qlist -I media-video/pipewire    && echo "  [OK] PipeWire"    || echo "  [FAIL] PipeWire!"
qlist -I media-video/wireplumber && echo "  [OK] WirePlumber" || echo "  [FAIL] WirePlumber!"
echo "[10.1] PipeWire autostart configured via gentoo-pipewire-launcher (restore-desktop.sh)"

echo "[OK] Phase 10 complete."

# ============================================================================
# PHASE 11: Machine-specific Hardware
# ============================================================================
echo ""
echo "=== PHASE 11: Hardware ==="

echo "[11.1] Configuring NVIDIA..."
if [[ -f "$CONFIGS/99-module-rebuild.install" ]]; then
    mkdir -p /etc/kernel/postinst.d
    cp "$CONFIGS/99-module-rebuild.install" /etc/kernel/postinst.d/99-module-rebuild.install
    chmod +x /etc/kernel/postinst.d/99-module-rebuild.install
fi

cat > /etc/modprobe.d/nvidia.conf <<EOF
options nvidia-drm modeset=1
blacklist nouveau
EOF
# TODO: if this is a laptop with Intel+NVIDIA Optimus, add NVreg_DynamicPowerManagement=0x02
#       and install $CONFIGS/prime-run to /usr/local/bin/

if [[ -f "$CONFIGS/prime-run" ]]; then
    cp "$CONFIGS/prime-run" /usr/local/bin/prime-run
    chmod +x /usr/local/bin/prime-run
    echo "  [OK] prime-run (Optimus) installed"
fi

echo "[11.x] Configuring zram-init..."
[[ -f "$CONFIGS/zram-init.conf" ]] && cp "$CONFIGS/zram-init.conf" /etc/conf.d/zram-init

echo "[11.x] Installing sysctl tuning..."
[[ -f "$CONFIGS/sysctl-performance.conf" ]] && \
    cp "$CONFIGS/sysctl-performance.conf" /etc/sysctl.d/99-${MACHINE}-performance.conf

# --- Desktop: no lid/suspend handling, always-on ---
echo "[11.x] Configuring always-on (no sleep/suspend)..."
mkdir -p /etc/elogind/logind.conf.d
cat > /etc/elogind/logind.conf.d/always-on.conf <<'ALWAYSON'
[Login]
HandleSuspendKey=ignore
HandleSuspendKeyLongPress=ignore
HandleHibernateKey=ignore
HandleHibernateKeyLongPress=ignore
HandleLidSwitch=ignore
HandleLidSwitchExternalPower=ignore
HandleLidSwitchDocked=ignore
IdleAction=ignore
ALWAYSON

echo "[11.x] Verifying firmware files..."
FW_FAIL=0
ls /lib/firmware/i915/kbl_dmc_*.bin 2>/dev/null | head -1 && echo "  [OK] i915 kbl DMC firmware" || echo "  [WARN] i915 DMC firmware missing"
ls /lib/firmware/nvidia/*/ 2>/dev/null | head -1 && echo "  [OK] NVIDIA firmware" || echo "  [WARN] NVIDIA firmware directory missing"

echo "[11.x] Installing emoji fontconfig..."
cat > /etc/fonts/local.conf <<'FONTEOF'
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>
  <alias><family>serif</family>     <prefer><family>Noto Color Emoji</family></prefer></alias>
  <alias><family>sans-serif</family><prefer><family>Noto Color Emoji</family></prefer></alias>
  <alias><family>monospace</family> <prefer><family>Noto Color Emoji</family></prefer></alias>
</fontconfig>
FONTEOF
fc-cache -f

echo "[OK] Phase 11 complete."

# ============================================================================
# PHASE 12: fstab (already generated by part2)
# ============================================================================
echo ""
echo "=== PHASE 12: fstab ==="
cat /etc/fstab
echo "[OK] Phase 12 complete."

# ============================================================================
# PHASE 13: Pre-reboot Verification
# ============================================================================
echo ""
echo "=== PHASE 13: Pre-reboot Verification ==="

FAIL=0; WARN=0

ls /boot/vmlinuz-* &>/dev/null && echo "[OK] Kernel installed" || { echo "[FAIL] No kernel!"; FAIL=$((FAIL+1)); }
grep -q menuentry /boot/grub/grub.cfg 2>/dev/null && echo "[OK] GRUB configured" || { echo "[FAIL] GRUB!"; FAIL=$((FAIL+1)); }
ls /boot/efi/EFI/Boot/bootx64.efi &>/dev/null && echo "[OK] EFI fallback copied" || echo "[WARN] No EFI fallback"

UUID_COUNT=$(grep -c UUID /etc/fstab || true)
[[ $UUID_COUNT -ge 3 ]] && echo "[OK] $UUID_COUNT UUID entries in fstab" || { echo "[FAIL] fstab missing entries!"; FAIL=$((FAIL+1)); }

qlist -I net-wireless/wpa_supplicant &>/dev/null && echo "[OK] wpa_supplicant" || { echo "[FAIL] wpa_supplicant!"; FAIL=$((FAIL+1)); }
qlist -I net-misc/networkmanager     &>/dev/null && echo "[OK] NetworkManager" || { echo "[FAIL] NetworkManager!"; FAIL=$((FAIL+1)); }

for svc in dbus NetworkManager display-manager acpid cronie sshd; do
    rc-update show default 2>/dev/null | grep -q "$svc" && echo "[OK] $svc enabled" || { echo "[FAIL] $svc NOT enabled!"; FAIL=$((FAIL+1)); }
done
rc-update show boot 2>/dev/null | grep -q elogind  && echo "[OK] elogind enabled"  || { echo "[FAIL] elogind!"; FAIL=$((FAIL+1)); }
rc-update show boot 2>/dev/null | grep -q zram     && echo "[OK] zram-init enabled" || { echo "[FAIL] zram-init!"; FAIL=$((FAIL+1)); }

qlist -I media-video/pipewire &>/dev/null && echo "[OK] PipeWire" || { echo "[FAIL] PipeWire!"; FAIL=$((FAIL+1)); }

id "$USERNAME" &>/dev/null && echo "[OK] User $USERNAME exists" || { echo "[FAIL] User!"; FAIL=$((FAIL+1)); }
groups "$USERNAME" 2>/dev/null | grep -q video && echo "[OK] $USERNAME in video group" || { echo "[FAIL] video group!"; FAIL=$((FAIL+1)); }
grep -q "^%wheel" /etc/sudoers 2>/dev/null && echo "[OK] sudo for wheel" || { echo "[FAIL] sudo!"; FAIL=$((FAIL+1)); }
grep -q 'DISPLAYMANAGER="lightdm"' /etc/conf.d/display-manager 2>/dev/null && echo "[OK] display-manager=lightdm" || { echo "[FAIL] DISPLAYMANAGER!"; FAIL=$((FAIL+1)); }

[[ $FW_FAIL -eq 0 ]] && echo "[OK] Required firmware present" || { echo "[FAIL] $FW_FAIL firmware file(s) missing!"; FAIL=$((FAIL+FW_FAIL)); }

echo ""
echo "============================================================"
if [[ $FAIL -eq 0 ]]; then
    echo "=== ALL CHECKS PASSED ($WARN warnings) ==="
    echo "============================================================"
    echo ""
    echo "Safe to exit chroot and reboot:"
    echo "  exit"
    echo "  umount -l /mnt/gentoo/dev{/shm,/pts,}"
    echo "  umount -R /mnt/gentoo"
    echo "  reboot"
    echo ""
    echo "Post-boot:"
    echo "  - Connect network via nmcli/nmtui"
    echo "  - Restore desktop: bash ~/gentoo-machines/shared/restore-desktop.sh"
    echo "  - Run tools/verify-install.sh for full verification"
else
    echo "=== $FAIL CHECKS FAILED ($WARN warnings) ==="
    echo "============================================================"
    echo "FIX FAILURES ABOVE BEFORE REBOOTING"
fi
