#!/bin/bash
# ============================================================================
# Gentoo Kernel Config - ASRock B550 Phantom Gaming-ITX/ax
# ============================================================================
# Generated by kernel-config-template.sh, then manually tuned for AMD platform
# Date: 2026-04-05
#
# CPU: AMD Ryzen 9 5950X 16-Core Processor (Zen 3, Vermeer)
# GPU: NVIDIA RTX 3060 Ti (GA104, Ampere) — proprietary nvidia-drivers
# WiFi: Intel AX200 (iwlwifi)
# Audio: Realtek ALC1220 (HDA) + NVIDIA HDMI
# Storage: MAXIO MAP1202 2TB NVMe (boot) + SATA SSD (unused)
# Platform: ASRock B550 (AMD 500-series chipset)
# Chassis: Desktop/Tower (mini-ITX)
#
# USAGE:
#   cd /usr/src/linux
#   make defconfig
#   bash /path/to/kernel_config.sh
#   make olddefconfig
#   make -j33 && make modules_install && make install
#
# BOOT STRATEGY: No initramfs — all root-path drivers built-in (=y)
# ============================================================================

set -euo pipefail

SC="./scripts/config"

if [[ ! -x "$SC" ]]; then
    echo "ERROR: Run this from /usr/src/linux (scripts/config not found)"
    exit 1
fi

echo "=== Applying ASRock B550 kernel config ==="
echo ""

# ==========================================================================
# PHASE 1: GENERAL / GENTOO
# ==========================================================================
echo "[Phase 1] General settings..."

$SC --enable IKCONFIG
$SC --enable IKCONFIG_PROC
$SC --set-str DEFAULT_HOSTNAME "asrock-b550"

$SC --enable GENTOO_LINUX
$SC --enable GENTOO_LINUX_INIT_SCRIPT
$SC --enable GENTOO_LINUX_PORTAGE
$SC --enable GENTOO_LINUX_UDEV

echo "  [OK] General"

# ==========================================================================
# PHASE 2: PROCESSOR - AMD Ryzen 9 5950X (Zen 3, Vermeer)
# ==========================================================================
echo "[Phase 2] Processor configuration..."

$SC --enable SMP
$SC --set-val NR_CPUS 32
# X86_NATIVE_CPU uses -march=native (build on target machine)
$SC --enable X86_NATIVE_CPU

# AMD CPU support (disable Intel)
$SC --enable CPU_SUP_AMD
$SC --disable CPU_SUP_INTEL

$SC --enable SCHED_MC
$SC --enable SCHED_SMT
$SC --enable SCHED_AUTOGROUP

# AMD P-State driver (Zen 2+, preferred over acpi-cpufreq)
$SC --enable X86_AMD_PSTATE
$SC --enable CPU_FREQ_GOV_PERFORMANCE
$SC --enable CPU_FREQ_GOV_POWERSAVE
$SC --enable CPU_FREQ_GOV_SCHEDUTIL
$SC --enable CPU_FREQ_DEFAULT_GOV_SCHEDUTIL

# AMD-specific
$SC --enable MICROCODE
$SC --enable MICROCODE_AMD
$SC --enable X86_X2APIC
$SC --enable AMD_IOMMU
$SC --enable AMD_IOMMU_V2

# AMD thermal — k10temp for Zen family
$SC --enable SENSORS_K10TEMP

# AMD Address Translation Library (Zen memory error reporting)
$SC --enable AMD_ATL

# EDAC — AMD MCE decoder
$SC --enable EDAC
$SC --module EDAC_DECODE_MCE
$SC --module EDAC_MCE_AMD

# KVM (AMD-V / SVM)
$SC --module KVM
$SC --module KVM_AMD

echo "  [OK] Processor"

# ==========================================================================
# PHASE 3: PERFORMANCE TUNING
# ==========================================================================
echo "[Phase 3] Performance tuning..."

$SC --enable PREEMPT
$SC --enable PREEMPT_DYNAMIC
$SC --enable HZ_1000
$SC --enable NO_HZ_IDLE

# Transparent Huge Pages
$SC --enable TRANSPARENT_HUGEPAGE
$SC --enable TRANSPARENT_HUGEPAGE_ALWAYS

# MGLRU (Multi-Gen LRU)
$SC --enable LRU_GEN
$SC --enable LRU_GEN_ENABLED

# KSM (Kernel Same-page Merging)
$SC --enable KSM

echo "  [OK] Performance"

# ==========================================================================
# PHASE 4: MEMORY / SWAP - zram
# ==========================================================================
echo "[Phase 4] Memory and zram..."

$SC --enable ZRAM
$SC --enable ZRAM_BACKEND_ZSTD
$SC --enable CRYPTO_ZSTD
$SC --enable ZSTD_COMPRESS
$SC --enable ZSTD_DECOMPRESS
$SC --set-str ZRAM_DEF_COMP "zstd"

$SC --enable SWAP
$SC --enable ZSWAP

$SC --enable LZ4_COMPRESS
$SC --enable LZ4HC_COMPRESS

echo "  [OK] Memory"

# ==========================================================================
# PHASE 5: STORAGE
# ==========================================================================
echo "[Phase 5] Storage..."

# NVMe MUST be =y (built-in) — boot drive, no initramfs
$SC --enable BLK_DEV_NVME
$SC --enable NVME_CORE

# SATA AHCI — module (secondary SATA SSD, NVMe is boot)
# AMD B550 500-series chipset SATA controller [1022:43eb]
$SC --enable ATA
$SC --module SATA_AHCI
$SC --module BLK_DEV_SD

# I/O scheduler
$SC --enable BLK_DEV_THROTTLING
$SC --enable IOSCHED_BFQ
$SC --enable BFQ_GROUP_IOSCHED

# USB storage
$SC --module USB_STORAGE
$SC --module USB_UAS

echo "  [OK] Storage"

# ==========================================================================
# PHASE 6: FILESYSTEMS
# ==========================================================================
echo "[Phase 6] Filesystems..."

# Root filesystem must be built-in (no initramfs)
$SC --enable EXT4_FS

# EFI partition must be built-in
$SC --enable VFAT_FS
$SC --enable NLS_CODEPAGE_437
$SC --enable NLS_ISO8859_1
$SC --enable FAT_FS
$SC --enable MSDOS_FS

# Other filesystems as modules
$SC --module BTRFS_FS
$SC --module XFS_FS
$SC --module EXFAT_FS
$SC --module NTFS3_FS
$SC --module FUSE_FS

$SC --enable TMPFS
$SC --enable PROC_FS
$SC --enable SYSFS

# EFI variables
$SC --enable EFI_PARTITION
$SC --enable EFIVAR_FS

echo "  [OK] Filesystems"

# ==========================================================================
# PHASE 7: GPU - NVIDIA RTX 3060 Ti (GA104, Ampere)
# ==========================================================================
echo "[Phase 7] GPU..."

$SC --enable DRM

# NVIDIA: out-of-tree proprietary driver (nvidia-drivers ebuild)
# DRM_QXL=m pulls in DRM_TTM_HELPER (nvidia build dep since kernel 6.11+)
$SC --module DRM_QXL
$SC --disable DRM_NOUVEAU
$SC --enable DRM_KMS_HELPER

# No Intel GPU (AMD CPU, discrete NVIDIA only)
$SC --disable DRM_I915

# Framebuffer
$SC --enable FB
$SC --enable FB_EFI
$SC --enable FRAMEBUFFER_CONSOLE
$SC --enable DRM_FBDEV_EMULATION

echo "  [OK] GPU"

# ==========================================================================
# PHASE 8: AUDIO - Realtek ALC1220 + NVIDIA HDMI
# ==========================================================================
echo "[Phase 8] Audio..."

$SC --enable SOUND
$SC --module SND
$SC --module SND_PCM
$SC --module SND_HWDEP
$SC --module SND_SEQ
$SC --module SND_TIMER
$SC --module SND_HRTIMER

# HDA Intel driver — module (works for AMD HDA too)
$SC --module SND_HDA_INTEL

# Codecs — Realtek ALC1220 + NVIDIA HDMI
$SC --module SND_HDA_CODEC_REALTEK
$SC --module SND_HDA_CODEC_HDMI
$SC --module SND_HDA_GENERIC

# HDA features
$SC --enable SND_HDA_HWDEP
$SC --enable SND_HDA_RECONFIG
$SC --enable SND_HDA_INPUT_BEEP
$SC --set-val SND_HDA_INPUT_BEEP_MODE 0
$SC --enable SND_HDA_PATCH_LOADER
$SC --enable SND_HDA_POWER_SAVE
$SC --set-val SND_HDA_POWER_SAVE_DEFAULT 1

# Disable SOF (HDA works natively)
$SC --disable SND_SOC_SOF_TOPLEVEL

echo "  [OK] Audio"

# ==========================================================================
# PHASE 9: WIFI - Intel AX200 (iwlwifi)
# ==========================================================================
echo "[Phase 9] WiFi..."

$SC --module CFG80211
$SC --enable CFG80211_WEXT
$SC --module MAC80211

# Intel WiFi (iwlwifi) — module, firmware from linux-firmware
$SC --module IWLWIFI
$SC --module IWLMVM

echo "  [OK] WiFi"

# ==========================================================================
# PHASE 10: BLUETOOTH - Intel (via AX200)
# ==========================================================================
echo "[Phase 10] Bluetooth..."

$SC --module BT
$SC --module BT_RFCOMM
$SC --module BT_BNEP
$SC --module BT_HIDP
$SC --module BT_HCIBTUSB
$SC --enable BT_HCIBTUSB_AUTOSUSPEND

# Intel BT firmware support
$SC --module BT_INTEL

echo "  [OK] Bluetooth"

# ==========================================================================
# PHASE 11: ETHERNET - Intel I225-V 2.5GbE (igc)
# ==========================================================================
echo "[Phase 11] Ethernet..."

$SC --module IGC

# USB Ethernet (for USB-C hubs/dongles)
$SC --module USB_RTL8152
$SC --module USB_NET_CDCETHER
$SC --module USB_NET_AX88179_178A

echo "  [OK] Ethernet"

# ==========================================================================
# PHASE 12: PLATFORM - AMD B550 / ASRock
# ==========================================================================
echo "[Phase 12] Platform drivers..."

# AMD Cryptographic Co-Processor (CCP/PSP)
$SC --module CRYPTO_DEV_CCP
$SC --module CRYPTO_DEV_SP_PSP

# AMD FCH watchdog (sp5100_tco)
$SC --module SP5100_TCO

# AMD FCH GPIO
$SC --module PINCTRL_AMD

# WMI
$SC --module ACPI_WMI
$SC --module WMI_BMOF

echo "  [OK] Platform"

# ==========================================================================
# PHASE 13: USB / HID
# ==========================================================================
echo "[Phase 13] USB and HID..."

$SC --enable USB
$SC --enable USB_XHCI_HCD
$SC --enable USB_XHCI_PCI
$SC --enable USB_EHCI_HCD
$SC --enable USB_EHCI_PCI

$SC --enable HID
$SC --enable USB_HID
$SC --module HID_MULTITOUCH
$SC --enable INPUT_MOUSEDEV
$SC --enable INPUT_EVDEV
$SC --enable INPUT_UINPUT

# Logitech wireless peripherals (HID++, Unifying receiver)
$SC --module HID_LOGITECH
$SC --module HID_LOGITECH_HIDPP
$SC --module HID_LOGITECH_DJ

echo "  [OK] USB/HID"

# ==========================================================================
# PHASE 14: I2C / SMBus - AMD FCH
# ==========================================================================
echo "[Phase 14] I2C and SMBus..."

# AMD FCH SMBus (piix4 driver, NOT i801 which is Intel)
$SC --module I2C_PIIX4
$SC --module I2C_SMBUS
$SC --module I2C_DEV

# SPD EEPROM reading (ee1004 for DDR4)
$SC --module EEPROM_EE1004

echo "  [OK] I2C"

# ==========================================================================
# PHASE 15: ACPI / POWER
# ==========================================================================
echo "[Phase 15] ACPI platform..."

$SC --enable PCI
$SC --enable PCIEPORTBUS
$SC --enable ACPI
$SC --enable ACPI_BUTTON
$SC --enable ACPI_FAN
$SC --enable ACPI_PROCESSOR
$SC --enable ACPI_THERMAL
$SC --enable ACPI_VIDEO

# Desktop: no battery or laptop backlight
$SC --disable ACPI_AC
$SC --disable ACPI_BATTERY

echo "  [OK] ACPI"

# ==========================================================================
# PHASE 16: SUSPEND / POWER
# ==========================================================================
echo "[Phase 16] Suspend and power..."

# S3 deep sleep supported on this board
$SC --enable SUSPEND
$SC --enable HIBERNATE_CALLBACKS
$SC --enable HIBERNATION

echo "  [OK] Suspend"

# ==========================================================================
# PHASE 17: NETWORKING / VPN
# ==========================================================================
echo "[Phase 17] Networking and VPN..."

$SC --enable NET
$SC --enable INET
$SC --enable IPV6
$SC --enable NETFILTER
$SC --enable NF_TABLES
$SC --module NF_CONNTRACK
$SC --module NF_NAT
$SC --module NFT_CT
$SC --module NFT_FIB
$SC --module NFT_REJECT

$SC --module TUN

# PPP for SSTP VPN
$SC --enable PPP
$SC --enable PPP_BSDCOMP
$SC --enable PPP_DEFLATE
$SC --enable PPP_MPPE
$SC --enable PPP_ASYNC
$SC --enable PPP_SYNC_TTY
$SC --enable PPP_MULTILINK
$SC --enable PPP_FILTER

echo "  [OK] Networking"

# ==========================================================================
# PHASE 18: FIRMWARE LOADING
# ==========================================================================
echo "[Phase 18] Firmware..."

$SC --enable FW_LOADER
$SC --enable FW_LOADER_USER_HELPER
$SC --set-str EXTRA_FIRMWARE ""

echo "  [OK] Firmware"

# ==========================================================================
# PHASE 19: EFI BOOT
# ==========================================================================
echo "[Phase 19] EFI boot..."

$SC --enable EFI
$SC --enable EFI_STUB
$SC --enable EFI_MIXED

echo "  [OK] EFI"

# ==========================================================================
# PHASE 20: CRYPTO - AMD hardware acceleration
# ==========================================================================
echo "[Phase 20] Hardware crypto..."

# AMD Zen CPUs support AES-NI / PCLMUL / SHA — same x86 ISA as Intel
# The kernel module names say "intel" but work on AMD too
$SC --module CRYPTO_AES_NI_INTEL
$SC --module CRYPTO_GHASH_CLMUL_NI_INTEL
$SC --module CRYPTO_POLYVAL_CLMUL_NI
$SC --module CRYPTO_SHA256_SSSE3
$SC --module CRYPTO_SHA512_SSSE3

# AMD CCP — hardware random number generator
$SC --module CRYPTO_DEV_CCP

echo "  [OK] Crypto"

# ==========================================================================
# PHASE 21: SECURITY
# ==========================================================================
echo "[Phase 21] Security..."

$SC --enable SECURITY
$SC --enable SECCOMP
$SC --enable SECURITY_YAMA
# AMD-specific mitigations (Spectre v2, etc.)
$SC --enable MITIGATION_RETPOLINE
$SC --enable MITIGATION_SRSO

echo "  [OK] Security"

# ==========================================================================
# PHASE 22: DISABLE UNNECESSARY HARDWARE
# ==========================================================================
echo "[Phase 22] Disabling unnecessary hardware..."

# Intel-specific (not present on AMD platform)
$SC --disable INTEL_MEI
$SC --disable INTEL_MEI_ME
$SC --disable INTEL_MEI_HDCP
$SC --disable INTEL_MEI_PXP
$SC --disable ITCO_WDT
$SC --disable I2C_I801
$SC --disable INTEL_ISH_HID
$SC --disable INTEL_RAPL

# No Intel GPU
$SC --disable DRM_I915

# Legacy / enterprise (not needed on desktop)
$SC --disable INFINIBAND
$SC --disable SOUND_OSS_CORE
$SC --disable PCMCIA
$SC --disable PARPORT

# iSCSI (not needed)
$SC --disable BE2ISCSI
$SC --disable BNX2I
$SC --disable CXGB4I
$SC --disable CXGB3I
$SC --disable QLA4XXX
$SC --disable SCSI_CXGB3_ISCSI
$SC --disable SCSI_CXGB4_ISCSI

# WiFi drivers not present
$SC --disable BRCMUTIL
$SC --disable BRCMFMAC
$SC --disable MWIFIEX
$SC --disable MWIFIEX_PCIE

# Apple / Surface (not present)
$SC --disable HID_APPLE
$SC --disable SENSORS_APPLESMC
$SC --disable APPLE_PROPERTIES
$SC --disable MACINTOSH_DRIVERS 2>/dev/null || true
$SC --disable SURFACE_PLATFORMS 2>/dev/null || true

echo "  [OK] Disabled"

# ==========================================================================
# DONE
# ==========================================================================
echo ""
echo "=== ASRock B550 kernel config applied ==="
echo ""
echo "Next steps:"
echo "  1. make olddefconfig              # resolve dependencies"
echo "  2. make menuconfig                # REVIEW CAREFULLY"
echo "  3. make -j33"
echo "  4. make modules_install"
echo "  5. make install"
echo ""
echo "Required firmware (from linux-firmware):"
echo "  - iwlwifi-cc-a0-*.ucode          (Intel AX200 WiFi)"
echo "  - intel/ibt-0040-0041.*           (Intel BT)"
echo "  - nvidia/ga104/*                  (RTX 3060 Ti)"
echo "  - amd-ucode/*                     (AMD microcode)"
