# /etc/conf.d/zram-init — MacBook Pro 12,1 (16GB RAM)
# 4GB zstd compressed swap

type0="swap"
flag0=""
size0="4096"
mlim0=""
back0=""
icmp0=""
imax0=""
ialg0=""
comp0="zstd"
labl0="zram_swap"
uuid0=""
args0=""

load_on_start="no"
unload_on_stop="no"
