#!/bin/bash
# ============================================================================
# Gentoo Kernel Config - Precision T5810
# ============================================================================
# Generated by kernel-config-template.sh from harvest data
# Date: 2026-03-11
#
# CPU: Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz
# GPU:  + NVIDIA (proprietary)
# WiFi: 
# Audio: hda (realtek)
# Storage: NVMe + SATA
# Platform: dell
#
# USAGE:
#   cd /usr/src/linux
#   make defconfig
#   bash /path/to/kernel_config.sh
#   make olddefconfig
#   make -j45 && make modules_install && make install
#
# BOOT STRATEGY: No initramfs — all root-path drivers built-in (=y)
# TODO: Review and verify all settings on live hardware
# ============================================================================

set -euo pipefail

SC="./scripts/config"

if [[ ! -x "$SC" ]]; then
    echo "ERROR: Run this from /usr/src/linux (scripts/config not found)"
    exit 1
fi

echo "=== Applying Precision T5810 kernel config ==="
echo ""

# ==========================================================================
# PHASE 1: GENERAL / GENTOO
# ==========================================================================
echo "[Phase 1] General settings..."

$SC --enable IKCONFIG
$SC --enable IKCONFIG_PROC
$SC --set-str DEFAULT_HOSTNAME "precision-t5810"

$SC --enable GENTOO_LINUX
$SC --enable GENTOO_LINUX_INIT_SCRIPT
$SC --enable GENTOO_LINUX_PORTAGE
$SC --enable GENTOO_LINUX_UDEV

echo "  [OK] General"

# ==========================================================================
# PHASE 2: PROCESSOR - Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz
# ==========================================================================
echo "[Phase 2] Processor configuration..."

$SC --enable SMP
$SC --set-val NR_CPUS 44
# MCORE2 is x86_32 only — does not exist on x86_64 builds.
# X86_NATIVE_CPU uses -march=native (must build on target machine).
$SC --enable X86_NATIVE_CPU


$SC --enable SCHED_MC
$SC --enable SCHED_SMT
$SC --enable SCHED_AUTOGROUP
$SC --enable X86_INTEL_PSTATE
# Performance-first workstation — max clocks, no power savings
$SC --enable CPU_FREQ_GOV_PERFORMANCE
$SC --enable CPU_FREQ_DEFAULT_GOV_PERFORMANCE
$SC --enable INTEL_IDLE
$SC --enable MICROCODE
$SC --enable X86_X2APIC

# Thermal/power
$SC --enable INTEL_RAPL
$SC --enable X86_PKG_TEMP_THERMAL
$SC --enable INTEL_POWERCLAMP
$SC --enable SENSORS_CORETEMP

# DPTF thermal framework
# TODO: verify DPTF INT340X device present in ACPI tables
$SC --enable ACPI_DPTF
$SC --module INT340X_THERMAL
$SC --module ACPI_THERMAL_REL
$SC --module INTEL_PCH_THERMAL
$SC --module PROC_THERMAL_MMIO_RAPL

# EDAC — ECC memory error detection (256GB DDR4 ECC)
# RAS is required for EDAC to be available
$SC --enable RAS
$SC --enable EDAC
$SC --enable PCI_MMCONFIG
$SC --module EDAC_DECODE_MCE
$SC --module EDAC_SBRIDGE  # Sandy Bridge through Broadwell-EP

# NUMA topology (multi-socket / server Xeon)
$SC --enable NUMA
$SC --enable X86_64_ACPI_NUMA
$SC --enable ACPI_NUMA

# KVM (bool — enable, not module)
$SC --enable KVM
$SC --module KVM_INTEL

echo "  [OK] Processor"

# ==========================================================================
# PHASE 3: PERFORMANCE TUNING
# ==========================================================================
echo "[Phase 3] Performance tuning..."

$SC --enable PREEMPT
$SC --enable PREEMPT_DYNAMIC
$SC --enable HZ_1000
$SC --enable NO_HZ_IDLE

# Transparent Huge Pages
$SC --enable TRANSPARENT_HUGEPAGE
$SC --enable TRANSPARENT_HUGEPAGE_ALWAYS

# MGLRU (Multi-Gen LRU)
$SC --enable LRU_GEN
$SC --enable LRU_GEN_ENABLED

# KSM (Kernel Same-page Merging)
$SC --enable KSM

echo "  [OK] Performance"

# ==========================================================================
# PHASE 4: MEMORY / SWAP - zram
# ==========================================================================
echo "[Phase 4] Memory and zram..."

$SC --enable ZRAM
$SC --enable ZRAM_BACKEND_ZSTD
$SC --enable CRYPTO_ZSTD
$SC --enable ZSTD_COMPRESS
$SC --enable ZSTD_DECOMPRESS
$SC --set-str ZRAM_DEF_COMP "zstd"

$SC --enable SWAP
$SC --enable ZSWAP

$SC --enable LZ4_COMPRESS
$SC --enable LZ4HC_COMPRESS

echo "  [OK] Memory"

# ==========================================================================
# PHASE 5: STORAGE
# ==========================================================================
echo "[Phase 5] Storage..."

# NVMe MUST be =y (built-in) — boot drive, no initramfs
$SC --enable BLK_DEV_NVME
$SC --enable NVME_CORE

# SATA AHCI — built-in if boot drive, module if secondary
# TODO: verify if SATA is boot drive or secondary
$SC --enable ATA
$SC --enable SATA_AHCI
$SC --enable BLK_DEV_SD

# I/O scheduler
$SC --enable BLK_DEV_THROTTLING
$SC --enable IOSCHED_BFQ
$SC --enable BFQ_GROUP_IOSCHED

# USB storage
$SC --module USB_STORAGE
$SC --module USB_UAS

# Optical drive (DVD-ROM)
$SC --enable BLK_DEV
$SC --enable BLK_DEV_SR
$SC --enable ISO9660_FS
$SC --enable UDF_FS

echo "  [OK] Storage"

# ==========================================================================
# PHASE 6: FILESYSTEMS
# ==========================================================================
echo "[Phase 6] Filesystems..."

# Root filesystem must be built-in (no initramfs)
$SC --enable EXT4_FS

# EFI partition must be built-in
$SC --enable VFAT_FS
$SC --enable NLS_CODEPAGE_437
$SC --enable NLS_ISO8859_1
$SC --enable FAT_FS
$SC --enable MSDOS_FS

# Other filesystems as modules
$SC --module BTRFS_FS
$SC --module XFS_FS
$SC --module EXFAT_FS
$SC --module FUSE_FS

$SC --enable TMPFS
$SC --enable PROC_FS
$SC --enable SYSFS

# EFI variables
$SC --enable EFI_PARTITION
$SC --enable EFIVAR_FS

echo "  [OK] Filesystems"

# ==========================================================================
# PHASE 7: GPU
# ==========================================================================
echo "[Phase 7] GPU..."

$SC --enable DRM

# NVIDIA: out-of-tree proprietary driver (nvidia-drivers ebuild)
# DRM_QXL=m pulls in DRM_TTM_HELPER (nvidia build dep since kernel 6.11+)
$SC --module DRM_QXL
$SC --disable DRM_NOUVEAU
$SC --enable DRM_KMS_HELPER

# Framebuffer
$SC --enable FB
$SC --enable FB_EFI
$SC --enable FRAMEBUFFER_CONSOLE
$SC --enable DRM_CLIENT_SELECTION
$SC --enable DRM_FBDEV_EMULATION

echo "  [OK] GPU"


# ==========================================================================
# PHASE 8: AUDIO
# ==========================================================================
echo "[Phase 8] Audio..."

$SC --enable SOUND
$SC --module SND
$SC --module SND_PCM
$SC --module SND_HWDEP
$SC --module SND_TIMER
$SC --module SND_HRTIMER

# HDA Intel driver — module
$SC --module SND_HDA_INTEL

# Codecs
$SC --module SND_HDA_CODEC_REALTEK
$SC --module SND_HDA_CODEC_HDMI
$SC --module SND_HDA_GENERIC

# HDA features
$SC --enable SND_HDA_HWDEP
$SC --enable SND_HDA_RECONFIG
$SC --enable SND_HDA_INPUT_BEEP
$SC --set-val SND_HDA_INPUT_BEEP_MODE 0
$SC --enable SND_HDA_PATCH_LOADER
$SC --set-val SND_HDA_POWER_SAVE_DEFAULT 1

# Disable SOF (HDA works natively)
$SC --disable SND_SOC_SOF_TOPLEVEL

echo "  [OK] Audio"

# ==========================================================================
# PHASE 9: WIFI — no WiFi hardware detected
# ==========================================================================
echo "[Phase 9] No WiFi hardware — disabling wireless..."

$SC --disable CFG80211
$SC --disable MAC80211
$SC --disable IWLWIFI
$SC --disable BRCMFMAC
$SC --disable MWIFIEX

echo "  [OK] WiFi disabled"

# ==========================================================================
# PHASE 10: BLUETOOTH
# ==========================================================================
echo "[Phase 10] Bluetooth..."

$SC --module BT
$SC --module BT_RFCOMM
$SC --module BT_BNEP
$SC --module BT_HIDP
$SC --module BT_HCIBTUSB
$SC --enable BT_HCIBTUSB_AUTOSUSPEND

# TODO: verify Bluetooth sub-driver from harvest data

echo "  [OK] Bluetooth"

# ==========================================================================
# PHASE 11: THUNDERBOLT
# ==========================================================================
echo "[Phase 11] Thunderbolt..."

$SC --module USB4
$SC --module INTEL_WMI_THUNDERBOLT

echo "  [OK] Thunderbolt"

# ==========================================================================
# PHASE 12: PLATFORM-SPECIFIC
# ==========================================================================
echo "[Phase 12] Platform drivers..."

# Dell platform — parent toggle required
$SC --enable X86_PLATFORM_DRIVERS_DELL
$SC --module DELL_WMI
$SC --module DELL_SMBIOS
$SC --enable DELL_SMBIOS_WMI
$SC --enable DELL_SMBIOS_SMM

echo "  [OK] Platform"

# ==========================================================================
# PHASE 16: USB / HID
# ==========================================================================
echo "[Phase 16] USB and HID..."

$SC --enable USB
$SC --enable USB_XHCI_HCD
$SC --enable USB_XHCI_PCI
$SC --enable USB_EHCI_HCD
$SC --enable USB_EHCI_PCI

$SC --enable HID
$SC --enable USB_HID
$SC --module HID_MULTITOUCH
$SC --enable INPUT_MOUSEDEV
$SC --enable INPUT_EVDEV
$SC --enable INPUT_UINPUT

echo "  [OK] USB/HID"

# ==========================================================================
# PHASE 17: USB ETHERNET
# ==========================================================================
echo "[Phase 17] USB Ethernet..."

$SC --enable NET_VENDOR_INTEL
$SC --module E1000E
# USB Ethernet (for USB-C hubs/dongles)
$SC --module USB_RTL8152
$SC --module USB_NET_CDCETHER
$SC --module USB_NET_AX88179_178A

echo "  [OK] Ethernet"

# ==========================================================================
# PHASE 18: I2C / SERIAL IO
# ==========================================================================
echo "[Phase 18] I2C and Serial IO..."

$SC --module I2C_I801

# Older chipset (C610/X99) — I2C via i801 SMBus only, no LPSS/Pinctrl

echo "  [OK] I2C"

# ==========================================================================
# PHASE 19: ACPI / POWER
# ==========================================================================
echo "[Phase 19] ACPI platform..."

$SC --enable PCI
$SC --enable PCIEPORTBUS
$SC --enable ACPI
$SC --enable ACPI_BUTTON
$SC --enable ACPI_FAN
$SC --enable ACPI_PROCESSOR
$SC --enable ACPI_THERMAL
$SC --enable ACPI_VIDEO

$SC --module ACPI_WMI

# Desktop/Tower: no battery or laptop backlight
$SC --disable ACPI_AC
$SC --disable ACPI_BATTERY

# MEI (Management Engine)
$SC --module INTEL_MEI
$SC --module INTEL_MEI_ME

# Watchdog
$SC --module ITCO_WDT
$SC --enable ITCO_VENDOR_SUPPORT

echo "  [OK] ACPI"

# ==========================================================================
# PHASE 20: SUSPEND / POWER
# ==========================================================================
echo "[Phase 20] Suspend and power..."

$SC --enable SUSPEND
$SC --enable HIBERNATE_CALLBACKS
$SC --enable HIBERNATION

echo "  [OK] Suspend"

# ==========================================================================
# PHASE 21: NETWORKING / VPN
# ==========================================================================
echo "[Phase 21] Networking and VPN..."

$SC --enable NET
$SC --enable INET
$SC --enable IPV6
$SC --enable NETFILTER
$SC --enable NF_TABLES
$SC --module NF_CONNTRACK
$SC --module NF_NAT
$SC --module NFT_CT
$SC --module NFT_FIB
$SC --module NFT_REJECT

$SC --module TUN

# PPP for SSTP VPN
$SC --enable PPP
$SC --enable PPP_BSDCOMP
$SC --enable PPP_DEFLATE
$SC --enable PPP_MPPE
$SC --enable PPP_ASYNC
$SC --enable PPP_SYNC_TTY
$SC --enable PPP_MULTILINK
$SC --enable PPP_FILTER

echo "  [OK] Networking"

# ==========================================================================
# PHASE 22: FIRMWARE LOADING
# ==========================================================================
echo "[Phase 22] Firmware..."

$SC --enable FW_LOADER
$SC --enable FW_LOADER_USER_HELPER
$SC --set-str EXTRA_FIRMWARE ""

echo "  [OK] Firmware"

# ==========================================================================
# PHASE 23: EFI BOOT
# ==========================================================================
echo "[Phase 23] EFI boot..."

$SC --enable EFI
$SC --enable EFI_STUB
$SC --enable EFI_MIXED

echo "  [OK] EFI"

# ==========================================================================
# PHASE 24: CRYPTO
# ==========================================================================
echo "[Phase 24] Hardware crypto..."

$SC --module CRYPTO_AES_NI_INTEL
$SC --module CRYPTO_GHASH_CLMUL_NI_INTEL
$SC --module CRYPTO_POLYVAL_CLMUL_NI
$SC --module CRYPTO_SHA256
$SC --module CRYPTO_SHA512

echo "  [OK] Crypto"

# ==========================================================================
# PHASE 25: SECURITY
# ==========================================================================
echo "[Phase 25] Security..."

$SC --enable SECURITY
$SC --enable SECCOMP
$SC --enable SECURITY_YAMA
$SC --enable MITIGATION_PAGE_TABLE_ISOLATION
$SC --enable MITIGATION_RETPOLINE

echo "  [OK] Security"

# ==========================================================================
# PHASE 26: DISABLE UNNECESSARY HARDWARE
# ==========================================================================
echo "[Phase 26] Disabling unnecessary hardware..."

$SC --disable CPU_SUP_AMD
$SC --disable DRM_AMDGPU
$SC --disable DRM_RADEON
# TODO: review GPU disables

# Legacy / enterprise (not needed on desktop/laptop)
$SC --disable INFINIBAND
$SC --disable SOUND_OSS_CORE
$SC --disable PCMCIA
$SC --disable PARPORT

# iSCSI (not needed)
$SC --disable BE2ISCSI
$SC --disable SCSI_CXGB3_ISCSI
$SC --disable SCSI_CXGB4_ISCSI


# Apple (not present)
$SC --disable HID_APPLE
$SC --disable SENSORS_APPLESMC
$SC --disable APPLE_PROPERTIES
$SC --disable MACINTOSH_DRIVERS 2>/dev/null || true
$SC --disable SURFACE_PLATFORMS 2>/dev/null || true

echo "  [OK] Disabled"

# ==========================================================================
# DONE
# ==========================================================================
echo ""
echo "=== Precision T5810 kernel config applied ==="
echo "TODO: Review all settings and verify on live hardware"
echo ""
echo "Next steps:"
echo "  1. make olddefconfig              # resolve dependencies"
echo "  2. make menuconfig                # REVIEW CAREFULLY"
echo "  3. make -j45"
echo "  4. make modules_install"
echo "  5. make install"
echo ""
echo "Required firmware (check harvest section 7 + 14):"
echo "  Install sys-kernel/linux-firmware for all module-loaded drivers"
