#!/bin/bash
# ============================================================================
# fingerprint-setup.sh — wire an enrolled fingerprint reader into PAM (Gentoo)
# ============================================================================
# Run as root, AFTER enrolling at least one finger as your normal user:
#
#     fprintd-enroll                      # as your user, not root
#     sudo bash shared/fingerprint-setup.sh
#
#     sudo WITH_SCREENSAVER=1 bash shared/fingerprint-setup.sh  # READ BELOW
#     sudo WITH_LIGHTDM=1 bash shared/fingerprint-setup.sh      # READ BELOW
#     sudo REVERT=1 bash shared/fingerprint-setup.sh         # undo everything
#
# Ported from the arch-machines repo, where this runs on an XPS 13 9315 whose
# reader is the SAME silicon as the 9510's — Goodix 27c6:63ac. What changes on
# Gentoo is packaging, not the PAM logic: see "GENTOO DIFFERENCES" below.
#
# WHAT IT TOUCHES, AND WHAT IT DELIBERATELY DOES NOT
#
#   /etc/pam.d/sudo               yes — and it is the only one that works well
#   /etc/pam.d/xfce4-screensaver  only with WITH_SCREENSAVER=1, and it BREAKS
#                                 password unlock — see below
#   /etc/pam.d/lightdm            only with WITH_LIGHTDM=1, untested here
#   /etc/pam.d/system-auth        NEVER
#
# system-auth is included by sudo, su, login, sshd and the display manager
# alike. Adding pam_fprintd there wires the reader into *every* authentication
# on the machine, including remote ones — and pam_fprintd on a session with no
# physical console prompts for a finger nobody can provide, so an ssh login
# sits there until it times out. Edit the specific services instead.
#
# On Gentoo there is a second reason: /etc/pam.d/system-auth is generated by
# sys-auth/pambase. Every pambase upgrade ships a new one, so a hand-edit
# there is a config-file conflict you have to re-resolve in dispatch-conf
# forever, and losing the merge silently disables your fingerprint — or
# silently re-enables it on ssh.
#
# `sufficient`, never `required`. A fingerprint that matches short-circuits
# the stack and succeeds; a fingerprint that fails, times out, or a reader
# that is not there at all falls straight through to the password prompt
# underneath. `required` would mean a dead sensor is a machine you cannot
# authenticate to.
#
# It goes ABOVE the include line, because PAM walks the auth stack in order:
# below the include, the password prompt has already run and the fingerprint
# is never reached.
#
# WHY THE SCREEN LOCKER IS OPT-IN AND NOT RECOMMENDED
#
# Measured on the arch xps-9315, and it is not a subtle failure: with
# pam_fprintd in /etc/pam.d/xfce4-screensaver, the finger unlocks the screen
# and the PASSWORD NO LONGER DOES.
#
# pam_fprintd is first in the stack, so the dialog's single PAM prompt becomes
# "Place your finger on the reader". xfce4-screensaver answers that one prompt
# with whatever you typed, pam_fprintd rejects it, and by the time the stack
# falls through to pam_unix and asks "Password:" the dialog has already spent
# its response. The journal says so by saying nothing: there is no pam_unix
# auth line at all, so pam_unix never ran. sudo does not have this problem
# because a terminal can carry on a real multi-prompt conversation; a one-shot
# unlock dialog cannot.
#
# `sufficient` is doing its job — the fallback is configured correctly and the
# locker simply cannot drive it. Keep fingerprint on sudo, where it works.
#
# GENTOO DIFFERENCES FROM THE ARCH ORIGINAL
#
#   1. USE=pam on sys-auth/fprintd is what builds pam_fprintd.so. Without it
#      the package installs, fprintd-enroll works, and PAM has nothing to load.
#   2. PAM modules do not live in /usr/lib/security here. The path is probed
#      rather than assumed, because it differs across profiles and the usr-merge.
#   3. No systemd. fprintd is D-Bus activated, so dbus must be running; there
#      is no fprintd service to add to a runlevel.
#   4. /etc/pam.d is under CONFIG_PROTECT, so an upgrade of sudo or pambase
#      leaves ._cfg0000_* files for dispatch-conf instead of overwriting your
#      edit. That is the Gentoo equivalent of Arch's .pacnew, and
#      `tools/update-system.sh config-update` already runs dispatch-conf.
#   5. libfprint version matters on this device — see the check in step 1.
# ============================================================================

set -uo pipefail
[[ $EUID -ne 0 ]] && { echo "ERROR: run with sudo"; exit 1; }

PAM_LINE="auth      sufficient  pam_fprintd.so"
MARKER="pam_fprintd.so"
BACKUP_DIR="/var/lib/kernel-update/config-backups"
PRIMARY_USER="${PRIMARY_USER:-${SUDO_USER:-chris}}"

ok()   { echo "  [OK]   $*"; }
warn() { echo "  [WARN] $*"; }
info() { echo "         $*"; }
fail() { echo "  [FAIL] $*"; }

# sudo only, by default and on purpose — see the block above about
# xfce4-screensaver. The two GUI targets are opt-in and both are known to be
# worse than they look.
FILES=(/etc/pam.d/sudo)
[[ "${WITH_SCREENSAVER:-0}" == "1" ]] && FILES+=(/etc/pam.d/xfce4-screensaver)
[[ "${WITH_LIGHTDM:-0}" == "1" ]] && FILES+=(/etc/pam.d/lightdm)

# ============================================================================
echo "=== 1. Preconditions ==="
# ============================================================================

# Gentoo installs PAM modules under $(getpam_mod_dir), which is /lib64/security
# on a classic profile and /usr/lib64/security after the usr-merge, with 32-bit
# profiles using lib rather than lib64. Probe instead of hardcoding.
PAM_MOD=""
for d in /lib64/security /usr/lib64/security /lib/security /usr/lib/security; do
    if [[ -f "$d/pam_fprintd.so" ]]; then PAM_MOD="$d/pam_fprintd.so"; break; fi
done
if [[ -z "$PAM_MOD" ]]; then
    fail "pam_fprintd.so not found in any known PAM module directory."
    info "Install it, and note that USE=pam is what actually builds it:"
    info "    echo 'sys-auth/fprintd pam' >> /etc/portage/package.use/fprintd"
    info "    emerge -av sys-auth/fprintd"
    info "If fprintd is already installed, it was built without USE=pam;"
    info "add the flag and re-emerge — the package will look unchanged otherwise."
    exit 1
fi
ok "pam_fprintd.so present at $PAM_MOD"

# fprintd is D-Bus activated. There is no fprintd init script to add to a
# runlevel — but with dbus down, nothing can activate it and every fingerprint
# prompt fails in a way that looks like a broken reader.
if command -v rc-service >/dev/null 2>&1; then
    if rc-service dbus status >/dev/null 2>&1; then
        ok "dbus is running (fprintd is D-Bus activated; it needs no runlevel entry)"
    else
        warn "dbus is not running — fprintd cannot be activated."
        info "    rc-service dbus start && rc-update add dbus default"
    fi
fi

# Goodix 27c6:63ac is claimed by libfprint's goodixmoc driver. Gentoo stable
# libfprint 1.94.7 with USE=-tod enrolls and verifies it on the XPS 9510
# (2026-08-27). An earlier version of this script warned that 1.94.7 was broken
# for this PID and told you to keyword ~amd64; that came from Ubuntu's
# 1.94.7+tod1 build, and the TOD blob is the variable, not the upstream
# version. The blob covers only the Goodix 53xc family, so on a 63ac it adds
# nothing and only muddies which code path runs. USE=tod is what this now
# warns about — the version is not the problem.
if lsusb 2>/dev/null | grep -qi '27c6:63ac'; then
    LFP=$(portageq best_version / sys-auth/libfprint 2>/dev/null | sed 's/.*libfprint-//')
    case "$LFP" in
        "") warn "Goodix 27c6:63ac detected but sys-auth/libfprint is not installed." ;;
        1.94.7*)
            ok "libfprint $LFP — the version verified working with this reader" ;;
        *)  info "Goodix 27c6:63ac detected; installed libfprint: $LFP"
            info "Verified on this hardware: 1.94.7 (USE=-tod). Others should be"
            info "fine, but only 1.94.7 has actually been exercised here." ;;
    esac
    # Ubuntu's failing build is 1.94.7+tod1. The Dell TOD blob covers only the
    # 53xc family, so on a 63ac it adds nothing and muddies which driver is in
    # play. Keep USE=-tod.
    if compgen -G "/usr/lib*/libfprint-2/tod-1" >/dev/null 2>&1; then
        warn "libfprint is built with USE=tod. The Dell TOD blob does not cover"
        info "27c6:63ac, so it cannot help here. Prefer USE=-tod."
    fi
fi

if [[ "${REVERT:-0}" != "1" ]]; then
    # An empty enrollment is not an error, but it makes every edit below a
    # no-op in practice, and that is worth saying out loud rather than
    # leaving someone to wonder why nothing prompts for a finger.
    # Match the per-finger lines, not a summary header. fprintd-list prints
    #     Fingerprints for user chris on Goodix MOC Fingerprint Sensor (press):
    #      - #0: right-index-finger
    # The device name is in that header, so anything anchored on wording
    # around it varies by reader. The "- #N:" lines do not.
    if su - "$PRIMARY_USER" -c 'fprintd-list "$USER"' 2>/dev/null \
         | grep -qE '^[[:space:]]*- #[0-9]+:'; then
        FINGERS=$(su - "$PRIMARY_USER" -c 'fprintd-list "$USER"' 2>/dev/null \
                    | grep -cE '^[[:space:]]*- #[0-9]+:')
        ok "$PRIMARY_USER has $FINGERS enrolled fingerprint(s)"
    else
        warn "$PRIMARY_USER has NO fingerprints enrolled."
        info "PAM will be wired up correctly and simply never match."
        info "Enroll first, as $PRIMARY_USER (not root):  fprintd-enroll"
    fi
fi

# ============================================================================
echo "=== 2. Backups ==="
# ============================================================================
mkdir -p "$BACKUP_DIR"
STAMP=$(date +%Y%m%d-%H%M%S)
for f in "${FILES[@]}"; do
    [[ -f "$f" ]] || continue
    cp -a "$f" "$BACKUP_DIR/$(basename "$f").${STAMP}.bak"
done
ok "originals copied to $BACKUP_DIR (suffix .${STAMP}.bak)"

# ============================================================================
if [[ "${REVERT:-0}" == "1" ]]; then
    echo "=== 3. Revert ==="
    for f in "${FILES[@]}"; do
        [[ -f "$f" ]] || continue
        if grep -q "$MARKER" "$f"; then
            sed -i "/${MARKER}/d" "$f"
            ok "removed pam_fprintd from $f"
        else
            info "$f — nothing to remove"
        fi
    done
    echo
    echo "Reverted. Password authentication is unchanged throughout."
    exit 0
fi

echo "=== 3. Wiring ==="
# ============================================================================
for f in "${FILES[@]}"; do
    if [[ ! -f "$f" ]]; then
        warn "$f does not exist — skipped"
        continue
    fi
    if grep -q "$MARKER" "$f"; then
        ok "$(basename "$f") — already wired"
        continue
    fi
    # Insert above the FIRST auth line, whatever it is: sudo includes
    # system-auth, lightdm includes system-login, xfce4-screensaver includes
    # system-auth with no leading comment. Anchoring on "the first line
    # starting with auth" is the one rule that holds for all three.
    if ! grep -qE '^\s*-?auth' "$f"; then
        warn "$(basename "$f") — no auth line found, skipped"
        continue
    fi
    awk -v line="$PAM_LINE" '
        !done && /^[[:space:]]*-?auth/ { print line; done=1 }
        { print }
    ' "$f" > "$f.tmp" && mv "$f.tmp" "$f"
    chmod 644 "$f"
    ok "$(basename "$f") — pam_fprintd added above the auth stack"
done

# ============================================================================
echo "=== 4. Verify ==="
# ============================================================================
F=0
for f in "${FILES[@]}"; do
    [[ -f "$f" ]] || continue
    if grep -q "$MARKER" "$f"; then
        # The fingerprint line must come before the include, or it never runs.
        FP=$(grep -n "$MARKER" "$f" | head -1 | cut -d: -f1)
        INC=$(grep -nE '^\s*-?auth\s+include' "$f" | head -1 | cut -d: -f1)
        if [[ -n "$INC" && "$FP" -gt "$INC" ]]; then
            fail "$(basename "$f") — pam_fprintd is BELOW the include; it will never run"
            F=$((F+1))
        else
            ok "$(basename "$f") — ordering correct"
        fi
    else
        fail "$(basename "$f") — not wired"
        F=$((F+1))
    fi
done

echo
if [[ $F -eq 0 ]]; then
    echo "=== WIRED — now prove it before you close this shell ==="
else
    echo "=== $F PROBLEM(S) — revert with: sudo REVERT=1 bash $0 ==="
fi
cat <<'NOTE'

  KEEP THIS ROOT SHELL OPEN. In a SECOND terminal, as your normal user:

      sudo -k && sudo true      # should prompt for a finger, then fall
                                # back to the password if you ignore it

  If sudo is broken instead, you still have this shell to undo it:

      REVERT=1 bash shared/fingerprint-setup.sh

  After any emerge of app-admin/sudo or sys-auth/pambase, run dispatch-conf.
  /etc/pam.d/sudo is CONFIG_PROTECTed, so the upgrade leaves ._cfg0000_sudo
  beside your edited file rather than replacing it — and blindly accepting the
  new version silently removes the fingerprint line.

  Match-on-Chip readers store templates on the sensor, not on disk. On a
  dual-boot machine Windows Hello writes to that same limited storage, so
  enrolling heavily on both sides can exhaust it or displace templates.
NOTE
exit $F
